title: Andrei Sim
logo : DSC_1673 copy.jpg
skin: "/assets/css/skins/dark.css"
#description: text below image
#show_downloads: true


gem "jekyll-theme-so-simple"
theme: jekyll-theme-so-simple
bundle install
